### ISSUE TITLE
When unlocking all recipes for a player, they receive every type of armored elytra

### ISSUE THREAD

**Issue by abigailwillow** [abbydiode/armored-elytra#1]
When a player uses the command `/recipe give @p *` the player also receives one of every type of armored elytra. This is due to the fact that the crafting recipe for armored elytra is tied to hidden recipes.

**Comment by abidbmt** [comment]
This is easily fixed by changing the advancement trigger to recipe_crafted instead of recipe_unlocked, make sure to remove the recipe removal code from the functions tho

**Comment by abigailwillow** [comment]
@abidbmt I really appreciate the suggestion, I wasn't aware of this. Would you like to open a PR for this so you are properly credited as a contributor?
