### ISSUE TITLE
Crafting amored elytra remove all enchantment

### ISSUE THREAD

**Issue by Thomas-Lecuppre** [abbydiode/armored-elytra#4]
As the title describe it, not matter what chestplate or enchant you put on it, when crafted with the elytra all enchantment disappears.

This is very embarrassing :)

Version used : 1.4.0
Minecraft server version : purpur 1.20.1
Minecraft user version : 1.20.1

**Comment by abigailwillow** [comment]
Thank you for opening this issue. As far as I'm aware it is not possible to transfer enchantments with the current implementation of this data pack, and the tools provided by Mojang. If you're aware of a method to transfer enchantments I'd encourage you to open a PR.
