### ISSUE TITLE
Various problems

### ISSUE THREAD

**Issue by FuzzyDark** [abbydiode/armored-elytra#5]
1. ### Forging:
- Item output display, does not use the added texture pack, instead, it displays a knowledge book named "_knowledge book_", whether the TP is server-requested or pre-installed.
- It gets rid of all pre-existing enchantments, both elytra's and chestplate's.
2. ### Enchanting:
- Once forged, one would assume you could enchant the netherite elytra (for this example), but even with Essentials, it's impossible to force enchant with **Protection**, getting "_Error: Enchantment PROTECTION_ENVIRONMENTAL: Specified enchantment cannot be applied to this itemstack_". Same happens **Thorns**.
- Using books on anvil, or native minecraft _enchant_ command, won't work either.

**Comment by abigailwillow** [comment]
Thank you for opening this detailed issue. I agree with your suggestions, but unfortunately, these are all limitations with the way the data pack is implemented. At least to my knowledge, right now these cannot be fixed. If you know a way to fix any of these issues, please open a PR and I'd be happy to review it!
