### ISSUE TITLE
Enchantments are lost and cant be applied again

### ISSUE THREAD

**Issue by freddy1301** [abbydiode/armored-elytra#6]
After you craft your Armored Elytra, both Items were enchanted in my case, the enchantments are gone. Also when I put the armored elytra in an enchanting table there are no enchantments shown also when using /enchant your cant apply the enchantments like protection.

Please add this feature, if it requires to be a paper plugin make it a paper plugin please 🙏🙏🙏

**Comment by abigailwillow** [comment]
Please see #5. Making a paper plugin takes quite a bit more effort than a data pack. Also, they serve a completely different purpose, as data packs don't require anything else installed, in contrast to plugins.
